export declare enum EViewerSetCamera {
    'top' = 0,
    'front' = 1,
    'right' = 2,
    'left' = 3,
    'back' = 4,
    'bottom' = 5,
    'top,front' = 6,
    'top right' = 7,
    'top,left' = 8,
    'top,back' = 9,
    'bottom,front' = 10,
    'bottom,right' = 11,
    'bottom,left' = 12,
    'bottom,back' = 13,
    'left,front' = 14,
    'front,right' = 15,
    'right,back' = 16,
    'back,left' = 17,
    'front,top,right' = 18,
    'back,top,right' = 19,
    'front,top,left' = 20,
    'back,top,left' = 21,
    'front,bottom,right' = 22,
    'back,bottom,right' = 23,
    'front,bottom,left' = 24,
    'back,bottom,left' = 25
}
